# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person-id.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='person-id.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fperson-id.proto\"Z\n\x0fPersonIDMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x04 \x01(\t2>\n\x0fPesronIDService\x12+\n\x05GetID\x12\x10.PersonIDMessage\x1a\x10.PersonIDMessageb\x06proto3'
)




_PERSONIDMESSAGE = _descriptor.Descriptor(
  name='PersonIDMessage',
  full_name='PersonIDMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PersonIDMessage.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='PersonIDMessage.first_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='PersonIDMessage.last_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='company_name', full_name='PersonIDMessage.company_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['PersonIDMessage'] = _PERSONIDMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PersonIDMessage = _reflection.GeneratedProtocolMessageType('PersonIDMessage', (_message.Message,), {
  'DESCRIPTOR' : _PERSONIDMESSAGE,
  '__module__' : 'person_id_pb2'
  # @@protoc_insertion_point(class_scope:PersonIDMessage)
  })
_sym_db.RegisterMessage(PersonIDMessage)



_PESRONIDSERVICE = _descriptor.ServiceDescriptor(
  name='PesronIDService',
  full_name='PesronIDService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=111,
  serialized_end=173,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetID',
    full_name='PesronIDService.GetID',
    index=0,
    containing_service=None,
    input_type=_PERSONIDMESSAGE,
    output_type=_PERSONIDMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PESRONIDSERVICE)

DESCRIPTOR.services_by_name['PesronIDService'] = _PESRONIDSERVICE

# @@protoc_insertion_point(module_scope)
